

class TestFail(Exception):
    pass


class TestError(Exception):
    pass